ruby '>= 3.1'
source 'https://rubygems.org'

gem 'middleman', '~> 4.5.0'
gem 'middleman-syntax', '~> 3.2'
gem 'middleman-autoprefixer', '~> 3.0'
gem 'middleman-sprockets', '~> 4.1'
gem 'sprockets', '~> 3.7'
gem 'sass'
gem 'rouge', '~> 3.21'
gem 'redcarpet', '~> 3.6.0'
gem 'nokogiri', '~> 1.19.2'
gem 'webrick'
gem 'terser'