name: Build

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version-file: ".ruby-version"
          bundler-cache: true

      - name: Middleman build
        run: bundle exec middleman build
